# Generated by Django 2.1.7 on 2019-04-08 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_selfintro'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=50, verbose_name='照片地址')),
                ('blog_num', models.IntegerField(verbose_name='博文数')),
                ('num_of_view', models.IntegerField(verbose_name='访客数')),
            ],
        ),
    ]
