# Generated by Django 2.1.7 on 2019-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_usermeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=10, verbose_name='博客类型')),
                ('url', models.CharField(max_length=30, verbose_name='资源地址')),
                ('title', models.CharField(max_length=30, verbose_name='题目')),
            ],
        ),
        migrations.DeleteModel(
            name='UserMeta',
        ),
    ]
