# Generated by Django 2.1.7 on 2019-04-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_auto_20190412_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='selfintro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
